### ISSUE TITLE
Add all authors to vignettes clusterGraph and graph

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/graph#22]
Add all authors to vignettes that originally were lacking authors

**Comment by LiNk-NY** [comment]
Note that you can check the authors based on the commit history via: 

```sh
## checkout early commit hash
git checkout e74dcbf

git shortlog -n -s -- inst/doc/GraphClass.Rnw
##     2  Robert Gentleman
##     2  Seth Falcon

git shortlog -n -s -- inst/doc/graph.Rnw
##     7  Robert Gentleman
##     2  Seth Falcon
##     1  Jeff Gentry
##     1  Paul Shannon

## return to devel checkout
git checkout devel
```

**Comment by jwokaty** [comment]
@LiNk-NY I noticed that Jeff and Paul aren't listed in the DESCRIPTION file. I wonder if they should still be listed as authors for graph.Rnw?

**Comment by LiNk-NY** [comment]
Yes, they could be added as authors to both the `DESCRIPTION` file and `graph.Rnw`

**Comment by jwokaty** [comment]
It looks like Robert added clusterGraph.Rnw at https://github.com/Bioconductor/graph/commit/60232b98e9b12efa888c8dbf514014e661fcc69d.

**Comment by jwokaty** [comment]
I will add the missing individuals to the DESCRIPTION file  as `ctb` and put those authors to the respective documents.

I think something like this would have been hard for a first-time contributor to figure out.

**Comment by LiNk-NY** [comment]
> It looks like Robert added clusterGraph.Rnw at [60232b9](https://github.com/Bioconductor/graph/commit/60232b98e9b12efa888c8dbf514014e661fcc69d).

Yes, and Jeff Gentry & Seth Falcon [modified it](https://github.com/Bioconductor/graph/commits/faf08a2838bfbec728e5c85385ade6cd0558b676/inst/doc/clusterGraph.Rnw?browsing_rename_history=true&new_path=vignettes/clusterGraph.Rmd&original_branch=devel) afterwards. 

> I will add the missing individuals to the DESCRIPTION file as `ctb` and put those authors to the respective documents.

Based on: https://r-pkgs.org/description.html#:~:text=aut%3A%20authors%2C%20those,contributions%2C%20like%20patches.

I would add them as `aut` rather than `ctb`. 

> I think something like this would have been hard for a first-time contributor to figure out.

I agree and mentors are crucial for these instances. 

Thanks!

**Comment by jwokaty** [comment]
Thanks for the follow up. I realized clusterGraph wasn't one of that we were looking at. The project is mostly inactive now.

**Comment by LiNk-NY** [comment]
Oops, I meant to add the commit history by author for `clusterGraph.Rnw`: 

```sh
git shortlog -n -s -- inst/doc/clusterGraph.Rnw
     2  Robert Gentleman
     1  Jeff Gentry
     1  Seth Falcon
```

Thanks!
